/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mehme
 */
public class ClassSearch extends javax.swing.JFrame {
    String mail;
    Connection conn;
    /**
     * Creates new form ClassSearch
     */
    public ClassSearch(String mail) {
        this.mail = mail;
        setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        class_input = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        class_search_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLASS SEARCH");

        class_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        class_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_inputActionPerformed(evt);
            }
        });
        class_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                class_inputKeyReleased(evt);
            }
        });

        class_search_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Day", "Duration", "Time", "Credit", "Type", "Instructor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        class_search_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(class_search_table);
        if (class_search_table.getColumnModel().getColumnCount() > 0) {
            class_search_table.getColumnModel().getColumn(0).setResizable(false);
            class_search_table.getColumnModel().getColumn(1).setResizable(false);
            class_search_table.getColumnModel().getColumn(2).setResizable(false);
            class_search_table.getColumnModel().getColumn(3).setResizable(false);
            class_search_table.getColumnModel().getColumn(4).setResizable(false);
            class_search_table.getColumnModel().getColumn(5).setResizable(false);
            class_search_table.getColumnModel().getColumn(6).setResizable(false);
        }

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(class_input, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(class_input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void class_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_class_inputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        UserScreen userScreen = new UserScreen(mail);
        userScreen.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void class_inputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_class_inputKeyReleased
        // TODO add your handling code here:
        populateCourseTable();
    }//GEN-LAST:event_class_inputKeyReleased

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField class_input;
    private javax.swing.JTable class_search_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void populateCourseTable() {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/du","root","1905");  
            Statement stmt=conn.createStatement();
            String query = "select code,day,duration,time,credit,iname,isurname "
                            +"from course inner join instructor on ciid = iid "
                            + "where code in (select ocode from online) and code like " + "'"+class_input.getText()+"%'";
            ResultSet rs=stmt.executeQuery(query); 
            String columns[] = {"Code","Day","Duration","Time","Credit","Type","Instructor"};
            int counter = 0;
            ArrayList<String[]> list = new ArrayList<>();
            while(rs.next()){
                counter++;
                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),"Online",rs.getString(6).replace("\"", "")+" " +rs.getString(7).replace("\"","")};
                list.add(data);
            }
            query = "select code,day,duration,time,credit,iname,isurname "
                            +"from course inner join instructor on ciid = iid "
                            + "where code in (select fcode from ftof) and code like " + "'"+class_input.getText()+"%'";
            rs=stmt.executeQuery(query);
            while(rs.next()){
                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),"Face To Face",rs.getString(6).replace("\"", "")+" " +rs.getString(7).replace("\"","")};
                list.add(data);
            }
            String result[][] = new String[list.size()][7];
            for(int i=0;i<list.size();i++){
                result[i] = list.get(i);
            }
            DefaultTableModel model = new DefaultTableModel(result,columns);
            class_search_table.setModel(model);   
            conn.close();  
        }catch(Exception e){ System.out.println(e);} 
    }
}
