/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.sql.PreparedStatement;


/**
 *
 * @author mehme
 */
public class CourseAddDrop extends javax.swing.JFrame {
    String mail;
    Connection conn;
    /**
     * Creates new form CourseAddDrop
     */
    public CourseAddDrop(String mail) {
        this.mail = mail;
        initComponents();
        populateAddBox();
        populateDropBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        course_adder = new javax.swing.JComboBox<>();
        course_dropper = new javax.swing.JComboBox<>();
        add_button = new javax.swing.JButton();
        drop_button = new javax.swing.JButton();
        info_label = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Course Add/Drop");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Add a Course");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Drop A Course");

        course_adder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        course_dropper.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        add_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add_button.setText("ADD");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        drop_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        drop_button.setText("DROP");
        drop_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drop_buttonActionPerformed(evt);
            }
        });

        info_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        info_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info_label.setText("Successfully Done");

        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(course_adder, javax.swing.GroupLayout.Alignment.LEADING, 0, 145, Short.MAX_VALUE)
                                .addComponent(add_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drop_button, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(course_dropper, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(course_adder, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(course_dropper))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(drop_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(info_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        UserScreen userscreen = new UserScreen(mail);
        userscreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
        System.out.println("***"+course_adder.getSelectedItem());
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/du","root","1905");  
            Statement stmt=conn.createStatement();
            String query = "select sid,Count(code) "
                            +"from student,enrolled,course "
                            + "where sid=ssid and code=ccode and letter is null and email = " + "'"+mail+"'";
            ResultSet rs=stmt.executeQuery(query);
            int sid = 0;
            int count=0;
            if(rs.next()){
                count = rs.getInt(2);
                sid = rs.getInt(1);
            }
            if(count == 5){
                info_label.setText("You cannot add more courses.");
            }else{
                Statement stmt2=conn.createStatement();
                String insert_query = "insert into enrolled (ssid,ccode,letter) "
                                       + "values ("+sid+",'"+course_adder.getSelectedItem()+"',"+"null)";
                course_dropper.addItem(course_adder.getSelectedItem().toString());
                course_adder.removeItemAt(course_adder.getSelectedIndex());
                boolean rs2 = stmt2.execute(insert_query);
                if(rs2) System.out.println("/"+ rs2);
                info_label.setText("Successfully added.");
            }
                      
            conn.close();  
        }catch(Exception e){ System.out.println(e);} 
    }//GEN-LAST:event_add_buttonActionPerformed

    private void drop_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drop_buttonActionPerformed
        // TODO add your handling code here:
        System.out.println("**"+course_dropper.getSelectedItem());
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/du","root","1905");  
            Statement stmt=conn.createStatement();
            String query = "select Count(code) "
                            +"from student,enrolled,course "
                            + "where sid=ssid and code=ccode and letter is null and email = " + "'"+mail+"'";
            ResultSet rs=stmt.executeQuery(query); 
            int count=0;
            if(rs.next()){
                count = rs.getInt(1);
            }
            if(count == 2){
                info_label.setText("You should take at least two course at a term.");
            }else{
                Statement stmt2=conn.createStatement();
                String select_query = "select ssid,code "
                            +"from student,enrolled,course "
                            + "where sid=ssid and code=ccode and letter is null and code = '"+course_dropper.getSelectedItem()+"' and email = " + "'"+mail+"'";
                
                ResultSet rs1 = stmt2.executeQuery(select_query);
                int ssid = 0;
                String code = "";
                if(rs1.next()){
                    ssid = rs1.getInt(1);
                    code = rs1.getString(2);
                    System.out.println("ssid: "+ rs1.getString(1) + " code: " + rs1.getString(2));
                }
                Statement stmt3=conn.createStatement();
                String delete_query = "delete from enrolled "
                                       + "where ssid = "+ssid+" and ccode = '" + code +"'";
                course_dropper.removeItemAt(course_dropper.getSelectedIndex());
                boolean rs2 = stmt3.execute(delete_query);
                if(rs2) System.out.println("/"+ rs2);
                info_label.setText("Successfully deleted.");
            }
                      
            conn.close();  
        }catch(Exception e){ System.out.println(e);} 
    }//GEN-LAST:event_drop_buttonActionPerformed

   private void populateAddBox(){
       try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/du","root","1905");  
            Statement stmt=conn.createStatement();
            String query = "select code "
                            +"from student,enrolled,course "
                            + "where sid=ssid and code=ccode and letter is null and email = " + "'"+mail+"'";
            String query2 = "select code "
                            + "from course "
                            + "where code not in (" +query +") "
                            + "order by code";
            ResultSet rs=stmt.executeQuery(query2); 
            
            ArrayList<String> list = new ArrayList<>();
            while(rs.next()){
                String data = rs.getString(1);
                list.add(data);
            }
            for(String str:list){
                course_adder.addItem(str);
            }             
            conn.close();  
        }catch(Exception e){ System.out.println(e);}
   }
   
   private void populateDropBox(){
       try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/du","root","1905");  
            Statement stmt=conn.createStatement();
            String query = "select code "
                            +"from student,enrolled,course "
                            + "where sid=ssid and code=ccode and letter is null and email = " + "'"+mail+"'";
            ResultSet rs=stmt.executeQuery(query); 
            
            ArrayList<String> list = new ArrayList<>();
            while(rs.next()){
                String data = rs.getString(1);
                list.add(data);
            }
            for(String str:list){
                course_dropper.addItem(str);
            }            
            conn.close();  
        }catch(Exception e){ System.out.println(e);} 
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> course_adder;
    private javax.swing.JComboBox<String> course_dropper;
    private javax.swing.JButton drop_button;
    private javax.swing.JLabel info_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
